version: '3'

services:
  postgres:
    image: postgres
  web: &base
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./config.env
  migrations:
      <<: *base
      command: python manage.py migrate --no-input
      ports: []
